 set rtp+=~/.vim/bundle/vundle/
 call vundle#rc()
 filetype plugin on
 filetype plugin indent off
 syntax enable
 set omnifunc=syntaxcomplete#Complete


 Bundle 'tpope/vim-rails.git'
 Bundle 'othree/html5.vim.git'
 Bundle 'moll/vim-node.git'
 Bundle 'AutoComplPop'
 Bundle 'vim-ruby/vim-ruby.git'
 Bundle 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
 Bundle 'jquery'
 Bundle 'L9'
 Bundle 'IndexedSearch'
 Bundle 'tpope/vim-haml.git'
 Bundle 'astashov/vim-ruby-debugger.git'
 Bundle 'chase/vim-ansible-yaml.git'
 Bundle 'scrooloose/nerdtree'
 Bundle 'tpope/vim-fugitive'
 Bundle 'tpope/vim-repeat'
 Bundle 'tpope/vim-markdown'
 Bundle 'tpope/vim-vividchalk'
 Bundle 'tpope/vim-surround'
 Bundle 'tsaleh/vim-align'
 Bundle 'altercation/vim-colors-solarized'
 Bundle 'junegunn/vim-easy-align'
 Bundle 'Lokaltog/vim-easymotion.git'
 Bundle 'FuzzyFinder'
 Bundle 'vim-scripts/SuperTab.git'
 Bundle 'Syntastic'
 Bundle 'majutsushi/tagbar.git'
 Bundle 'godlygeek/tabular.git'
 Bundle 'burnettk/vim-angular.git'
 Bundle 'sidorares/node-vim-debugger.git'
 Bundle 'nvie/vim-flake8.git'
 Bundle 'nvie/vim-pep8.git'
 Bundle 'kchmck/vim-coffee-script.git'
 Bundle 'groenewege/vim-less.git'
 Bundle 'skammer/vim-css-color.git'
 Bundle 'hail2u/vim-css3-syntax.git'
 Bundle 'tristen/vim-sparkup.git'
 Bundle 'twe4ked/vim-peepopen.git'
 Bundle 'greyblake/vim-preview.git'
 Bundle 'nanotech/jellybeans.vim.git'
 Bundle 'matthewsimo/angular-vim-snippets.git'
 Bundle 'tpope/vim-cucumber'
 Bundle 'slim-template/vim-slim'
 Bundle 'skalnik/vim-vroom'
 Bundle 'tpope/vim-endwise'
 Bundle 'tpope/vim-bundler'
 Bundle 'ervandew/supertab'
